name: Ejecutar prueba unitaria

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Ejecutar prueba unitaria
      run: |
        python test.py
